spring:
  datasource:
    url: jdbc:mysql://116.62.123.56:3306/star_blog
    username: root
    password: '0224'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: true
  devtools:
    restart:
      enabled: true

