spring:
  datasource:
    url: jdbc:mysql://116.62.123.56:3306/star_blog
    username: root
    password: '0224'
#    primary:
#      url: jdbc:mysql://116.62.123.56:3306/star_blog&user=root&password=0224
#    backup:
#      url: jdbc:mysql://rm-bp1v19620520reqv5jo.mysql.rds.aliyuncs.com:3306/star_blog&user=star&password=Gx990224
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: true
  devtools:
    restart:
      enabled: true
#server:
#  ssl:
#    key-store-password: g2UlH4ih
#    key-store-type: PKCS12
#    key-store: classpath:cert/3720955_star0224.com.pfx